"""empty message

Revision ID: 35fca522d209
Revises: 
Create Date: 2021-08-30 10:48:25.455031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '35fca522d209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('education_yrs', sa.Integer(), nullable=True))
    race_enum_postgres = postgresql.ENUM('white_non_latino', 'white_latino', 'black', 'asian_or_pacific', 'american_indian', 'multiple', 'undefined', name='raceenum', create_type=False)
    race_enum_postgres.create(op.get_bind(), checkfirst=False)
    op.add_column('subject', sa.Column('race', race_enum_postgres, nullable=True))
    op.add_column('visit', sa.Column('bmi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'bmi')
    op.drop_column('subject', 'race')
    op.drop_column('subject', 'education_yrs')
    # ### end Alembic commands ###
