"""empty message

Revision ID: 8450b363cf25
Revises: 35fca522d209
Create Date: 2021-10-06 09:46:34.517521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '8450b363cf25'
down_revision = '35fca522d209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('image', 'blocking_processing_id')
    preprocessed_enum_postgres = postgresql.ENUM('none', 'minimal1', 'locked', 'failed', name='preprocessedenum', create_type=False)
    preprocessed_enum_postgres.create(op.get_bind(), checkfirst=False)
    op.add_column('image', sa.Column('preprocessed', preprocessed_enum_postgres, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('blocking_processing_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
